### PR TITLE
Python code to list recent podcast to Pushover

### PR DESCRIPTION
**Pull request by theorbitofmercury**

### CODE REVIEW

**Comment by dvehrs** [comment]
Sorry for the delay looking at this.   It looks good but we may need to make a few small changes.   It will probably be easier to make them on my end but we can do it either way.

Proposed changes:
1.  Filename change:  From README to push-new-mp3.README  This is just because that's the way we've done it in the past and it's good to stay consistent for users.   
2. Author/Developer credit.  I don't see any line in either the script or the README giving credit where it is due.  This has been done in a couple different ways in previous scripts.  First is just listing an AUTHOR: NAME in the README and the second in the script we add a comment near the top of the script:  "# Copyright: (c) 2021 NAME"

Any thoughts on these changes?

Dave

**Comment by theorbitofmercury** [comment]
Hi Dave
I am happy with your proposed modifications. Please make them yourself as you know what you are doing more than me.
My python code(unchanged) is still working well for me and I find it very useful as I use M.A.L.P/Android  for control, Snapcast server(on same Pi as PODGET and mpd) to broadcast to several snapclient's(Pi's/PC's/Chromebook) and Pushover to see what's new on my Android phone to listen to all the pods PODGET downloads on my Raspberry Pi.
Cheers Mike
Screenshot_20210215-175155

**Comment by dvehrs** [comment]
Hi Mike,

I tried to upload the new version to Debian today, and got informed by my mentor that I gave you some bad advice regarding the copyright statement for the package to be included within the Debian Package.

I advised you to just use "Copyright (c) Mike Webb" and that was the beginning of what needed to be done but there is a bit more.  Since this is your script, if you would like it to be packaged with Podget then we need to expand it just a bit so the licenses are in line.  

Like so:
"""
    Copyright (C) 2021 Mike Webb                                                                                                                                          
                                                                                                                                                                          
    This program is free software: you can redistribute it and/or modify                                                                                                  
    it under the terms of the GNU General Public License as published by                                                                                                  
    the Free Software Foundation, either version 3 of the License, or                                                                                                     
    (at your option) any later version.                                                                                                                                   
                                                                                                                                                                          
    This program is distributed in the hope that it will be useful,                                                                                                       
    but WITHOUT ANY WARRANTY; without even the implied warranty of                                                                                                        
    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the                                                                                                         
    GNU General Public License for more details.                                                                                                                          
                                                                                                                                                                          
    You should have received a copy of the GNU General Public License                                                                                                     
    along with this program.  If not, see <https://www.gnu.org/licenses/>. 
"""

Now this will release it under the same license that Podget is released under.  

Second change will be removing the copyright statement from the README and changing it to "Contributed by Mike Webb".

Then third and final change will be adding a statement to the debian/copyright file that reads:
"""
  Files: SCRIPTS/v0.8.8/push-new-mp3.py3                                                                                                                                  
  Copyright: 2021 Mike Webb                                                                                                                                               
  License: GPL-3.0+  
"""

I should have done the last one but as you can see I'm not that experienced at getting the licensing right for contributed scripts.

What do you think?  Can I make the changes?  Is this inline with how you expected the script to be licensed and released?

Thanks,
Dave

**Comment by theorbitofmercury** [comment]
Hi DaveI am happy for you to make the changes as requiredRegardsMikeOn 9 Sep 2021 11:07 pm, Dave Vehrs ***@***.***> wrote:
Hi Mike,
I tried to upload the new version to Debian today, and got informed by my mentor that I gave you some bad advice regarding the copyright statement for the package to be included within the Debian Package.
I advised you to just use "Copyright (c) Mike Webb" and that was the beginning of what needed to be done but there is a bit more.  Since this is your script, if you would like it to be packaged with Podget then we need to expand it just a bit so the licenses are in line.
Like so:
"""
Copyright (C) 2021 Mike Webb
This program is free software: you can redistribute it and/or modify                                                                                                  
it under the terms of the GNU General Public License as published by                                                                                                  
the Free Software Foundation, either version 3 of the License, or                                                                                                     
(at your option) any later version.                                                                                                                                   
                                                                                                                                                                      
This program is distributed in the hope that it will be useful,                                                                                                       
but WITHOUT ANY WARRANTY; without even the implied warranty of                                                                                                        
MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the                                                                                                         
GNU General Public License for more details.                                                                                                                          
                                                                                                                                                                      
You should have received a copy of the GNU General Public License                                                                                                     
along with this program.  If not, see <https://www.gnu.org/licenses/>. 

"""
Now this will release it under the same license that Podget is released under.
Second change will be removing the copyright statement from the README and changing it to "Contributed by Mike Webb".
Then third and final change will be adding a statement to the debian/copyright file that reads:
"""
Files: SCRIPTS/v0.8.8/push-new-mp3.py3
Copyright: 2021 Mike Webb
License: GPL-3.0+
"""
I should have done the last one but as you can see I'm not that experienced at getting the licensing right for contributed scripts.
What do you think?  Can I make the changes?  Is this inline with how you expected the script to be licensed and released?
Thanks,
Dave

—You are receiving this because you authored the thread.Reply to this email directly, view it on GitHub, or unsubscribe.Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by dvehrs** [comment]
Thanks Mike!

I've made the changes and they will appear in version 0.8.10

**Pull request merged**
