### PR TITLE
support Free, Net and OpenBSD

### PR DESCRIPTION
**Pull request by llua**
with the same requirements as darwin

### CODE REVIEW

**Comment by dvehrs** [comment]
Interesting use of the hash command.  I haven't seen that trick before.  

Now I've only been able to do a bit of testing on it and everything appears OK, but I do not have a Darwin machine to test on.  Assuming they have gsed and sed installed, this will direct them to the correct sed.  Right?    On my machine with very limited testing it appears to work in just that manner.

I'm mildly concerned with the case statement on line 1188.  Is there no way to identify the various BSDs by their uname response?  Is it really best to use a wildcard here?    And if we are forced to use a wildcard, maybe we want to add a comment for what OSes we expect to match there.    

Might we be better off to make it "FreeBSD|NetBSD|OpenBSD" instead of a wildcard?

Mostly I like this better that what was in its place.   Makes the script easier to maintain.

Final question.  When we do merge this, how do you want to be known in the changelog?

**Comment by llua** [comment]
I was kinda expecting to be questioned about the ambiguous glob there. i assumed even more exotic OSs would definitively need coreutils to run the script. after viewing an illumos system's coreutils package though your idea sounds better, since the commands with conflicting names are placed in `/usr/gnu/bin` instead of prefixed with `g`. so assuming an illumos user has their `PATH` setup  correctly, they could also use podget.
I'll explicitly list the supported BSDs.

Eric Cook <llua@gmx.com> is fine

**Comment by dvehrs** [comment]
OK, for testing I've merged this push request into the branch dev-llua-coreutils.   This is so it includes the things I've been working on for the next release.   Other than a few conflicts because of differences between Master and Dev, it went fine.  I've only done a couple of test runs so far but it appears to work fine.  

I noticed that you updated the case statement like we discussed.  Thank you.

So I think the next step will be more testing for this version.  With any luck, we will be able to push a release soon.

Dave

**Comment by dvehrs** [comment]
I also updated the Changelog with a proposed entry for this submission.  Nothing there is final, I often change those right up to release day.  Take a look at it, this is a significant enough contribution that it should be appropriately mentioned.  So any ideas you have will be considered.  
Dave

**Comment by dvehrs** [comment]
OK, I've done quite a bit of testing on Linux and it all appears to be working fine.  

I've installed a copy of FreeBSD 12.1 onto virtualbox for testing and at first it appears to work.  Unfortunately it runs into problems shortly after that.  

We use the FILTER_OPTIONS function to remove certain keywords from feed categories or names so that we can tweak how Podget is processing each feed.  This is where we can configure things like username and password to access a feed if we need it.  Unfortunately there appears to be a difference in the way Bash on BSD processes the regex we use than it does on Linux.

I ran into it on the first feed I had that included the OPT_CONTENT_DISPOSITION option.  This option enables renaming a downloaded file with the name provided by the Content-Disposition header received from the server.  

The problem is within the regex I use to detect it.
    if [[ "${!FILTER_ITEM}" =~ ^(.*[[:space:]]|)OPT_CONTENT_DISPOSITION.*$ ]]; then

On Linux, this will catch the keyword if it is the first word or a later in a name or category.  Unfortunately BSD appears to not like the use of parenthesis in this manner.  If I remove the ( |) parts, it works just fine to detect the keyword when it anything but the first word.  I've tried escaping those three symbols and no luck so far.  

The problem is when these items are not detected, they are not used and they are not removed.

**Comment by dvehrs** [comment]
OK I might have a solution.  The problem appears to be caused on BSD by the "OR NOTHING", but if we change that to |[[:space:]]?)  then it's looking for zero or one spaces.  Technically one space is equivalent to the other side of the OR so all we really care about is the zero spaces.  Have to test if this plays well on Linux now....  fun fun.

**Comment by dvehrs** [comment]
OK one small change and it appears to be working through the tests slowly by surely.

(.+[[:space:]]|[[:space:]]?)  appears the be the regex prefix that we need.  I'm about 90% through testing on FreeBSD and 20% on Linux.  So a bit to go.

**Comment by llua** [comment]
no rush.

**Comment by dvehrs** [comment]
Added basic instructions to the INSTALL file for FreeBSD and OpenBSD.

**Comment by dvehrs** [comment]
OK, got a NetBSD image working in Virtualbox but experienced a few issues that I wasn't sure what was causing them.  So I installed NetBSD to an old laptop to discover that the issues followed me so it wasn't Virtualbox, it was something in my configuration choices. 

The first issue was related to IPv4 and IPv6 addresses.  My network is configured for IPv4 and every other OS I've tested on seems to automatically set a preference for that address family.  However NetBSD just took the addresses in the order they were given by the DNS server.  So when verbosity was set to anything above 2, this created a few messages that were mildly concerning.  At verbosity 2, we would see:  "failed: No route to host."  At verbosity 3 or 4, we would see the same message but with a "connecting to <hostname>|IPv6 address|:80".  Testing revealed that adding "--prefer-family=IPv4" to the wget options made the issue go away so I added that as a Commonly Used Option for Wget base options.  Hopefully anyone else that experiences that problem will try it.

The second issue had to with verifying SSL certificates.  The ca-certificates package for NetBSD does not appear to be as complete as those on other systems because it had trouble verifying some Amazon or Let's Encrypt certificates that other systems had no problem with.  However this was easily resolved by using the "--no-check-certificate" option in the wget base options so I didn't test much further.  This could have been caused by a failure on my part to add more certificates to the configuration and my only excuse was I was trying to emulate what a novice user like myself would experience attempting to configure podget on NetBSD.

 I also added basic instructions for NetBSD to the INSTALL file.  

Still need to finish testing on OpenBSD and Linux but things look very good to move to the head DEV branch soon.

**Comment by dvehrs** [comment]
OK,finished testing against FreeBSD and Linux.  Everything looks good so I merged the dev-llua-coreutils branch with the dev branch so it is all included with the next version.  I've thought of a couple small options I would like to add to account for some minor usage issues.  With any luck I will get those working quickly and be able to do some testing for release.  

This may be my last comment here for a while, I will leave this open until I merge the dev branch with master.  I do not plan to use the automated merge offered here because I merged it by hand into the dev-llua-coreutils branch (and now into the dev branch).  So you're fixes are in just a slightly different path than the default github one.  

Dave

**Comment by dvehrs** [comment]
OK, it's in the master branch and tagged as release 0.8.7.  

Thanks again!

Dave

**Pull request merged**
